CREATE TABLE IF NOT EXISTS prestamo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre VARCHAR(100) NOT NULL,
    ISBN INT NOT NULL,
    socio VARCHAR(100) NOT NULL,
    fecha VARCHAR(100) NOT NULL
);